version: '3.1'

services:

    qr-flow-mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: qrflow
        volumes:
            - ./mongo/db:/data/db
    
    qr-flow-mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8008:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: qr-flow-mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
